title: My Blog
description: "A simple Jekyll blog powered by GitHub Pages"
baseurl: "" # leave empty for main site
url: "https://mysistersdogmolly.github.io" # change USERNAME to your GitHub username

theme: minima
plugins:
  - jekyll-feed
